/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-03-03T09:00:24.053Z")

@Api(value = "foo", description = "the foo API")
public interface FooApi {

    @ApiOperation(value = "Get foo", nickname = "getFoo", notes = "Foo", response = String.class, tags={ "foo", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = String.class),
        @ApiResponse(code = 400, message = "Invalid status value") })
    @RequestMapping(value = "/foo",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> getFoo(@NotNull @ApiParam(value = "Foo id", required = true) @Valid @RequestParam(value = "id", required = true) String id);

}
